drop table if exists member CASCADE;
create table member(
                       id bigint unique not null auto_increment,
                       # id에 generated by default as identity를 해주면 null값이 들어왔을 때, 자동으로 값을 채워준다.
                           # Mysql 계열에서는 안 되는 듯 싶다.
                           name varchar(255),
                       PRIMARY key (id)
);


SELECT * from member;

INSERT into member(name) values('JunyHarang');
INSERT into member(name) values('HelloJunyHarang');


CREATE user'junyharang'@'%' identified by '[비밀번호]';

grant all privileges on SpringStudy.* TO 'junyharang'@'%';